name: cool-retro-term-lbo # you probably want to 'snapcraft register <name>'
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A good looking terminal emulator which mimics the old cathode display...
description: |
  cool-retro-term is a terminal emulator which mimics the look and feel of the old cathode tube screens. It has been designed to be eye-candy, customizable, and reasonably lightweight.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

apps:
  cool-retro-term:
    command: desktop-launch cool-retro-term
    desktop: usr/share/applications/cool-retro-term.desktop
    # plugs: []

parts:
  cool-retro-term:
    plugin: qmake
    source: https://github.com/Swordfish90/cool-retro-term.git
    source-tag: '1.0.1'
    build-packages:
      - qt5-qmake
      - qtdeclarative5-dev
    stage-packages:
      - qmlscene
      - qt5-default
      - libqt5qml-graphicaleffects
      - qml-module-qt-labs-folderlistmodel
      - qml-module-qt-labs-settings
      - qml-module-qtquick-controls
      - qml-module-qtquick-dialogs
      - qtdeclarative5-localstorage-plugin
      - qtdeclarative5-qtquick2-plugin
      - qtdeclarative5-window-plugin
    qt-version: qt5
    after: [desktop-qt5]
